use std::str::FromStr;
use lalrpop_util::ParseError;

grammar;

use crate::lists::LorV;

pub Packet: LorV = {
  "[" <Comma<Packet>> "]" => LorV::L(<>),
  <Int32> => LorV::V(<>),
  "[]" => LorV::L(vec![]),
}

Comma<T>: Vec<T> = {
  <mut v:(<T> ",")*> <e:T> => { v.push(e); v }
}

Int32: i32 = {
  r"-?[0-9]+" =>? i32::from_str(<>)
    .map_err(|_| ParseError::User {
      error: "Number can't be parsed"
    })
};
