[package]
name = "day22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.utils]
path = "../utils"

[dependencies]
grid = "0.9.0"
pad = "0.1.6"
itertools = "0.10.5"
